languageCode = "en-us"
baseurl = "https://docs.nlp.ac.cn/"
title = "API Site"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
        unsafe = true

[module]
[module.hugoVersion]
[[module.imports]]
# This is replaced in go.mod to point to the directory above.
path="github.com/bep/docuapi/v2"

[params]
search = true
maxMenuDepth = 3 # (optional) available options are: 1, 2, or 3 (default: 2)
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "shell"
name = "Shell"
[[params.language_tabs]]
key = "javascript"
name = "JavaScript"
[[params.language_tabs]]
key = "python"
name = "Python"
[[params.language_tabs]]
key = "php"
name = "PHP"
[[params.language_tabs]]
key = "java"
name = "Java"
[[params.language_tabs]]
key = "go"
name = "Go"


#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "API Site"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Sign Up for a Developer Key</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true

[languages.cn]
languageName = "中文"
weight = 1
title = "API文档"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>点击这里获取apiKey</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]

[languages.cn.blackfriday]
# Norwegian uses angled quotes
angledQuotes = true
hrefTargetBlank = true

[security]
[security.exec]
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME|SSH_AUTH_SOCK|USERPROFILE|XDG_CONFIG_HOME|HTTP_PROXY|HTTPS_PROXY)$']
